# ============================================================
# CLV CivilTools - Knowledge Base Upload Staging
# ============================================================

$ErrorActionPreference = "Stop"

$RepoRoot = (git rev-parse --show-toplevel).Trim()
$UploadFolder = Join-Path $RepoRoot "KnowledgeBase\UPLOAD"
$UploadRelative = "KnowledgeBase/UPLOAD"
$Manifest = Join-Path $UploadFolder "UPLOAD_MANIFEST.txt"

Set-Location $RepoRoot

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " CLV Knowledge Base Upload Staging" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# ------------------------------------------------------------
# Verify branch
# ------------------------------------------------------------

$Branch = (git branch --show-current).Trim()

if ($Branch -ne "work") {
    Write-Host "ERROR: Current branch is '$Branch'." -ForegroundColor Red
    Write-Host "This workflow is intended for the work branch." -ForegroundColor Yellow
    exit 1
}

# ------------------------------------------------------------
# Verify repository state
#
# Changes inside KnowledgeBase/UPLOAD are expected.
# Everything else must be clean before staging an upload.
# ------------------------------------------------------------

$StatusLines = @(git status --short --untracked-files=all)

$OutsideUpload = @(
    $StatusLines | Where-Object {
        if ([string]::IsNullOrWhiteSpace($_) -or $_.Length -lt 4) {
            return $false
        }

        $Path = $_.Substring(3).Trim('"').Replace('\', '/')
        $Path -notlike "$UploadRelative/*"
    }
)

if ($OutsideUpload.Count -gt 0) {
    Write-Host "ERROR: There are changes outside the UPLOAD folder." -ForegroundColor Red
    Write-Host ""
    foreach ($Line in $OutsideUpload) {
        Write-Host "  $Line" -ForegroundColor Red
    }
    Write-Host ""
    Write-Host "Resolve or commit those changes before running the upload staging script." -ForegroundColor Yellow
    exit 1
}

# ------------------------------------------------------------
# Verify upload folder
# ------------------------------------------------------------

if (-not (Test-Path -LiteralPath $UploadFolder -PathType Container)) {
    Write-Host "ERROR: Upload folder does not exist:" -ForegroundColor Red
    Write-Host "  $UploadFolder"
    Write-Host ""
    exit 1
}

# ------------------------------------------------------------
# Find upload files
#
# README.md is permanent.
# Existing manifest is generated by this script.
# ------------------------------------------------------------

$Files = @(
    Get-ChildItem -LiteralPath $UploadFolder -File -Recurse |
        Where-Object {
            $_.Name -ne "README.md" -and
            $_.Name -ne "UPLOAD_MANIFEST.txt"
        }
)

if ($Files.Count -eq 0) {
    Write-Host "No files found to stage for upload." -ForegroundColor Yellow
    exit 0
}

Write-Host "Files found for upload:" -ForegroundColor Green
Write-Host ""

$RelativeFiles = @()

foreach ($File in $Files) {
    $Relative = $File.FullName.Substring($RepoRoot.Length + 1).Replace('\', '/')
    $RelativeFiles += $Relative
    Write-Host "  $Relative"
}

Write-Host ""

$Confirm = Read-Host "Stage these files for GitHub upload? (Y/N)"

if ($Confirm -notmatch "^[Yy]$") {
    Write-Host "Upload staging cancelled." -ForegroundColor Yellow
    exit 0
}

# ------------------------------------------------------------
# Create manifest
# ------------------------------------------------------------

$ManifestLines = @(
    "# CLV Knowledge Base Upload Manifest"
    "# Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    "# Temporary files staged from KnowledgeBase/UPLOAD."
    "# README.md is permanent and is not listed."
    ""
)

$ManifestLines += $RelativeFiles

$ManifestLines | Set-Content -LiteralPath $Manifest -Encoding UTF8

# ------------------------------------------------------------
# Stage upload folder only
# ------------------------------------------------------------

Write-Host ""
Write-Host "Staging KnowledgeBase/UPLOAD..." -ForegroundColor Cyan

git add -- "KnowledgeBase/UPLOAD"

# ------------------------------------------------------------
# Show staged files
# ------------------------------------------------------------

Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Host " Upload staging prepared" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
Write-Host ""

git diff --cached --name-status

Write-Host ""
Write-Host "No commit or push was performed." -ForegroundColor Yellow
Write-Host "Review the staged changes in Visual Studio before committing." -ForegroundColor Yellow
Write-Host ""
