<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework Condition="'$(GisTestTargetFramework)' == ''">net8.0</TargetFramework>
    <TargetFramework Condition="'$(GisTestTargetFramework)' != ''">$(GisTestTargetFramework)</TargetFramework>
    <AssemblyName>OSGeo.MapGuide.Geometry</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
